# Generated by Django 3.0.8 on 2020-11-19 10:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_patient', models.CharField(max_length=20, unique=True, verbose_name='Code Patient')),
                ('sexe', models.CharField(blank=True, max_length=15, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de Naissance')),
                ('date_enrolement', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name="Date d'enrolement")),
                ('Date_de_mise_sous_ARV', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de mise sous traitement ARV')),
                ('nom_conseiller', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom et Prénoms du conseiller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_rdv', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de Rendez-Vous')),
                ('motif', multiselectfield.db.fields.MultiSelectField(choices=[('ARV', 'ARV'), ('CV', 'CV'), ('ETP', 'ETP')], max_length=10, verbose_name='Motif de Rendez-Vous')),
                ('code_patient', models.ManyToManyField(to='mytrack.Patient', verbose_name='code du patient')),
            ],
            options={
                'verbose_name': 'Rendez-Vous',
                'verbose_name_plural': 'Rendez-Vous',
            },
        ),
        migrations.CreateModel(
            name='Respect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_respect', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de Respect')),
                ('motif_respect', models.CharField(blank=True, max_length=30, null=True, verbose_name='Respect de Rendez-Vous')),
            ],
            options={
                'verbose_name': 'Respect de RDV',
                'verbose_name_plural': 'Respect des RDV',
            },
        ),
        migrations.CreateModel(
            name='SuiviRdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_rappel', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de Rappel')),
                ('moyen_rappel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Moyen de Rappel')),
                ('resultat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Resultat')),
                ('respect_rdv', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True, verbose_name='Respect de Rendez-Vous')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv', to='mytrack.Patient')),
                ('date_respect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv', to='mytrack.Respect')),
                ('rdv', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv', to='mytrack.Rdv')),
            ],
            options={
                'verbose_name': 'Suivi de RDV',
                'verbose_name_plural': 'Suivis des RDV',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_derniere_dispensation', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de dernière dispensation')),
                ('nb_jour_traitement', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jour de traitement')),
                ('dernier_regime_dispense', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dernier redime dispensé')),
                ('date_fin_traitement', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de fin de Traitement')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='mytrack.Patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
            },
        ),
        migrations.CreateModel(
            name='ContactSujetIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_contact', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code du sujet contact')),
                ('type_contact', models.CharField(blank=True, choices=[('1', 'Conjoint'), ('2', 'Autre partenaire sexuel'), ('3', 'Enfant biologique < 15 ans'), ('4', 'Frères /Sœurs   < 15 ans (de index < 15 ans)'), ('5', "Père/Mère(de l'index < 15 ans)")], max_length=1, null=True, verbose_name='Type de contact')),
                ('sexe_contaxt', models.CharField(blank=True, choices=[('1', 'Masculin'), ('2', 'Feminin '), ('3', 'Transgenre')], max_length=5, null=True, verbose_name='Sexe du contact')),
                ('date_naissance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de naissance')),
                ('statut_identification', models.CharField(blank=True, choices=[('1', 'VIH +'), ('2', 'VIH -'), ('3', 'Inconnu')], max_length=1, null=True, verbose_name="Statut VIH à l'enregistrement")),
                ('date_depistage', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de dépistage')),
                ('resultat_depistage', models.CharField(blank=True, choices=[('1', 'Positif'), ('2', 'Négatif')], max_length=1, null=True, verbose_name='Résultat de dépistage')),
                ('date_mise_ARV', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de Mise sous ARV')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_sujet_index', to='mytrack.Patient')),
            ],
            options={
                'verbose_name': 'Contact du sujet Index',
                'verbose_name_plural': 'Contacts du sujet Index',
            },
        ),
        migrations.CreateModel(
            name='ChargeVirale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_prelevement', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 19))], verbose_name='Date de prélèvement')),
                ('resultat_CV', models.CharField(blank=True, max_length=20, null=True, verbose_name='Résultat Charge Virale')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_virale', to='mytrack.Patient')),
            ],
            options={
                'verbose_name': 'Charge Virale',
                'verbose_name_plural': 'Charges Virales',
            },
        ),
    ]
